[WIP] adding developer options to entry point: these still need to be set in .env
maintaina/containers pull request #4
Opened 2021-12-02 13:41 UTC by boekhorstb1

Currently not sure how I can test this

2021-12-03 15:51 UTC, boekhorstb1 commented
OK, current code is working for the base installation.
I will test once more on Monday if it works for the Groupware, but I think it is fine.

Will change maintaina/deployments according and send a link when that is done (probably monday)

2021-12-03 16:04 UTC, boekhorstb1 commented
Updated [maintaina/deployments](https://github.com/maintaina/deployments/pull/9) accordingly

2021-12-06 15:39 UTC, boekhorstb1 commented
checked also for groupware-webmail and all is working, at least on my machine ;)

2021-12-17 11:08 UTC, ralflang requested changes

2021-12-17 11:08 UTC, ralflang commented on base/bin/entrypoint.sh
> +	echo "ending installatin of developer tools"
installatin -> installation

2021-12-17 11:08 UTC, ralflang commented on base/bin/entrypoint.sh
> +    zypper -n in vim wget mc iputils curl less bind-utils;
Add a variable to add more/custom software.

2022-01-07 10:20 UTC, boekhorstb1 commented on base/bin/entrypoint.sh
> +	echo "ending installatin of developer tools"
ok ich hab die Rechtschreibung angepasst

2022-01-07 10:20 UTC, boekhorstb1 commented on base/bin/entrypoint.sh
> +    zypper -n in vim wget mc iputils curl less bind-utils;
ok. Werde CUSTOM_TOOLS variable hinzufügen und testen

2022-01-07 12:37 UTC, boekhorstb1 commented
Ok, I added a CUSTOM_TOOLS variable. I also updated the .env.dist in the basic-setup here: https://github.com/maintaina/deployments/pull/9/files

2022-02-17 09:14 UTC, ralflang approved these changes
Looks good. Thank you.

2022-02-17 09:14 UTC, merged